version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./provisioning/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NODE_ENV=development
    ports:
      - 80:80
    depends_on:

      - client


      - server



  client:
    build: .
    volumes:
      - .:/code:cached
    command: yarn client:watch -- --host 0.0.0.0 --port 8080
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
      - 35729:35729



  server:
    build: .
    volumes:
      - .:/code:cached
#    depends_on:
#      - postgresql
#      - mongodb
#      - elasticsearch
    command: yarn server:watch
    environment:
      - NODE_ENV=development
    ports:
      - '9229:9229'

###
# Postgresql configuration
###
#
#  postgresql:
#    image: postgres:9.5.5
#    environment:
#      - POSTGRES_USER=flow-coding-dojo
#      - POSTGRES_PASSWORD=flow-coding-dojo
#      - POSTGRES_DB=flow-coding-dojo
#
###

###
# Mongodb configuration
###
#
#  mongodb:
#    image: mongo
#
###

###
# Elasticsearch configuration
###
#
#  elasticsearch:
#    image: elasticsearch
#
###

