// flow-typed signature: d16f60716006da568818d2fc5584b3b5
// flow-typed version: <<STUB>>/healthcheck-fastit_vgit+ssh://git@github.com:fastit/health-check.git#1.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'healthcheck-fastit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'healthcheck-fastit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'healthcheck-fastit/source/index' {
  declare module.exports: any;
}

declare module 'healthcheck-fastit/test/check' {
  declare module.exports: any;
}

declare module 'healthcheck-fastit/test/getClient' {
  declare module.exports: any;
}

declare module 'healthcheck-fastit/test/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'healthcheck-fastit/source/index.js' {
  declare module.exports: $Exports<'healthcheck-fastit/source/index'>;
}
declare module 'healthcheck-fastit/test/check.js' {
  declare module.exports: $Exports<'healthcheck-fastit/test/check'>;
}
declare module 'healthcheck-fastit/test/getClient.js' {
  declare module.exports: $Exports<'healthcheck-fastit/test/getClient'>;
}
declare module 'healthcheck-fastit/test/server.js' {
  declare module.exports: $Exports<'healthcheck-fastit/test/server'>;
}
