// flow-typed signature: f996f22e1bca68602ec72d97e385ab81
// flow-typed version: <<STUB>>/loopback-boot_v2.26.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loopback-boot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loopback-boot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loopback-boot/browser' {
  declare module.exports: any;
}

declare module 'loopback-boot/lib/bundler' {
  declare module.exports: any;
}

declare module 'loopback-boot/lib/compiler' {
  declare module.exports: any;
}

declare module 'loopback-boot/lib/config-loader' {
  declare module.exports: any;
}

declare module 'loopback-boot/lib/executor' {
  declare module.exports: any;
}

declare module 'loopback-boot/lib/require' {
  declare module.exports: any;
}

declare module 'loopback-boot/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loopback-boot/browser.js' {
  declare module.exports: $Exports<'loopback-boot/browser'>;
}
declare module 'loopback-boot/index' {
  declare module.exports: $Exports<'loopback-boot'>;
}
declare module 'loopback-boot/index.js' {
  declare module.exports: $Exports<'loopback-boot'>;
}
declare module 'loopback-boot/lib/bundler.js' {
  declare module.exports: $Exports<'loopback-boot/lib/bundler'>;
}
declare module 'loopback-boot/lib/compiler.js' {
  declare module.exports: $Exports<'loopback-boot/lib/compiler'>;
}
declare module 'loopback-boot/lib/config-loader.js' {
  declare module.exports: $Exports<'loopback-boot/lib/config-loader'>;
}
declare module 'loopback-boot/lib/executor.js' {
  declare module.exports: $Exports<'loopback-boot/lib/executor'>;
}
declare module 'loopback-boot/lib/require.js' {
  declare module.exports: $Exports<'loopback-boot/lib/require'>;
}
declare module 'loopback-boot/lib/utils.js' {
  declare module.exports: $Exports<'loopback-boot/lib/utils'>;
}
