// flow-typed signature: 96baa33146d50cb11401f5754867444b
// flow-typed version: <<STUB>>/redux-localstorage-filter_v0.1.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-localstorage-filter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-localstorage-filter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-localstorage-filter/lib/filter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-localstorage-filter/lib/filter.js' {
  declare module.exports: $Exports<'redux-localstorage-filter/lib/filter'>;
}
