// flow-typed signature: e89f7343a14c827d340afc3be483fc40
// flow-typed version: <<STUB>>/redux-localstorage_v1.0.0-rc4/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-localstorage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-localstorage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-localstorage/lib/actionTypes' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/adapters/AsyncStorage/adapter' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/adapters/AsyncStorage/index' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/adapters/localStorage/adapter' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/adapters/localStorage/index' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/adapters/sessionStorage/index' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/bufferActions' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/index' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/mergePersistedState' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/persistState' {
  declare module.exports: any;
}

declare module 'redux-localstorage/lib/persistStateMiddleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-localstorage/lib/actionTypes.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/actionTypes'>;
}
declare module 'redux-localstorage/lib/adapters/AsyncStorage/adapter.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/adapters/AsyncStorage/adapter'>;
}
declare module 'redux-localstorage/lib/adapters/AsyncStorage/index.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/adapters/AsyncStorage/index'>;
}
declare module 'redux-localstorage/lib/adapters/localStorage/adapter.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/adapters/localStorage/adapter'>;
}
declare module 'redux-localstorage/lib/adapters/localStorage/index.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/adapters/localStorage/index'>;
}
declare module 'redux-localstorage/lib/adapters/sessionStorage/index.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/adapters/sessionStorage/index'>;
}
declare module 'redux-localstorage/lib/bufferActions.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/bufferActions'>;
}
declare module 'redux-localstorage/lib/index.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/index'>;
}
declare module 'redux-localstorage/lib/mergePersistedState.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/mergePersistedState'>;
}
declare module 'redux-localstorage/lib/persistState.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/persistState'>;
}
declare module 'redux-localstorage/lib/persistStateMiddleware.js' {
  declare module.exports: $Exports<'redux-localstorage/lib/persistStateMiddleware'>;
}
